---
name: controller
services:
  controller:
    image: dmbrownlee/controller:latest
    build:
      context: .
      args:
        username: ${IMAGE_USERNAME}
        uid: ${IMAGE_UID}
        gid: ${IMAGE_GID}
    hostname: controller
    domainname: ${IMAGE_DNS_SEARCH_DOMAIN}
    volumes:
      - home:/home/${IMAGE_USERNAME}
      - home__ssh:/home/${IMAGE_USERNAME}/.ssh
      - etc_ssh:/etc/ssh
    ports:
      - "2222:22"
    networks:
      - controller
    dns:
      - ${IMAGE_DNS_NAMESERVER}
    dns_search:
      - ${IMAGE_DNS_SEARCH_DOMAIN}
    dns_opt:
      - ndots:2

networks:
  controller:

volumes:
  home:
  home__ssh:
  etc_ssh:
