---
name: controller
services:
  controller:
    hostname: controller.${LOCAL_DOMAIN}
    domainname: ${LOCAL_DOMAIN}
    container_name: controller
    image: dmbrownlee/controller:latest
    build:
      context: .
    environment:
      ANSIBLE_PULL_OPTIONS: ${ANSIBLE_PULL_OPTIONS}
      ANSIBLE_PULL_VARS_FILE_URL: ${ANSIBLE_PULL_VARS_FILE_URL}
    volumes:
      - ${CONTROLLER_HOME_PATH}:/home
      - ${CONTROLLER_SSH_PATH}:/etc/ssh
      - ${CONTROLLER_BACKUP_PATH}:/backups
    dns:
      - ${NS1_IP}
      - ${NS2_IP}
    dns_search: ${LOCAL_DOMAIN}
    ports:
      - name: ssh
        host_ip: 127.0.0.1
        published: "${CONTROLLER_HOST_PORT}"
        protocol: tcp
        target: 22
