---
name: controller
services:
  controller:
    hostname: controller
    image: dmbrownlee/controller:latest
    build:
      context: .
    environment:
      ANSIBLE_PULL_OPTIONS: ${ANSIBLE_PULL_OPTIONS}
      ANSIBLE_PULL_VARS_FILE_URL: ${ANSIBLE_PULL_VARS_FILE_URL}
    volumes:
      - home:/home
      - etc_ssh:/etc/ssh
    dns: ${DNS_IP}
    dns_search: ${LOCAL_DOMAIN}
    networks:
      SERVER_VLAN:
        ipv4_address: ${CONTROLLER_IP}

networks:
  SERVER_VLAN:
    external: true

volumes:
  home:
  etc_ssh:
